config/routes.rb
UserAuth::Application.routes.draw do
  get "verifyreset/new"

  get "password_resets/new"

  resources :users do
    collection { post :import }
  end

  resources :attendances do
    collection { post :import }
    collection {post :go}
  end

  resources :password_resets
  resources :verifyreset

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  match '/attendances/create/:event_id/:user_id/:points/:role',
    :controller => :attendances,
    :action => "create",
    :as => "create"
  match '/users/id/:id',
    :controller => :users,
    :action => "id"

  match '/users/firstname/:firstname',
    :controller => :users,
    :action => "firstname"

  match '/users/lastname/:lastname',
    :controller => :users,
    :action => "lastname"

  match '/users/firstname/:firstname/lastname/:lastname',
    :controller => :users,
    :action => "firstname_lastname"

  match '/users/yr/:year',
    :controller => :users,
    :action => "yr"

  match '/users/course/:course_id',
    :controller => :users,
    :action => "course"

  match '/events/id/:id',
    :controller => :events,
    :action => "id"

  match '/events/name/:name',
    :controller => :events,
    :action => "name"

  match '/events/eventclass/:eventclass_id',
    :controller => :events,
    :action => "eventclass"

  match '/events/venue/:venue',
    :controller => :events,
    :action => "venue"

  
  match ':controller(/:action(/:id))(.:format)'

  
  match "signup", 
    :to => "users#new"

  
  match "edit", 
    :to => "users#edit",
    :via => :post
  
  match "update", 
    :to => "users#update"

  match "change_password/:idnum", 
    :to => "users#change_password"

  match "destroy", 
    :to => "users#destroy"
  
  match "index", 
    :to => "users#index"

  match "edit", 
    :to => "events#edit"

  match "login",
    :to => "sessions#login"

  match "verify/:id",
    :to => "password_resets#verify",
    :as => "verify"

  match "logout", 
    :to => "sessions#logout"

  match "home", 
    :to => "sessions#home"

  match "profile/:user_id", 
    :to => "sessions#profile"

  match "event/:event_id", 
    :to => "sessions#viewevent",
    :as => "viewevent"

  match "edit/event/:event_id", 
    :to => "sessions#editevent",
    :as => "editevent"

  match "reset/:id/:answer", 
    :to => "password_resets#reset",
    :as => "reset"

  match "/setting/:idnum", 
    :to => "sessions#setting",
    :as => "setting"

  match "changepw/:idnum", 
    :to => "sessions#changepw",
    :as => "changepw"

  match "eventcalendar", 
    :to => "sessions#eventcalendar"

  match "event_to_csv/:id", 
    :to => "sessions#event_to_csv", 
    :as => "eventcsv"

  match "generatedb", 
    :to => "sessions#generatedb"

  match "dormerlist_to_csv", 
    :to => "sessions#dormerlist_to_csv", 
    :as => "dormerlistcsv"

  match "progress/:user_id", 
    :to => "sessions#progress"

  match "regfile",
    :to => "sessions#upload_reg_file"

  match "message", 
    :to => "sessions#message"

  match "newevent", 
    :to => "sessions#newevent"

  match "viewmembers", 
    :to => "sessions#viewmembers"

  match "dormcouncil", 
    :to => "sessions#view_dorm_council"

   

  match "create", 
    :to => "messages#create"

  match "consolidated", 
    :to => "consolidated#index"
  
  match "/secgen_dashboard", 
    :to => "secgen_dashboard#index", 
    :as => :secgen_dashboard
  match "/secgen_dashboard/import_dormers", 
    :to => "secgen_dashboard#import_dormers", 
    :as => :import_dormers
  match "/secgen_dashboard/import", 
    :to => "secgen_dashboard#import", 
    :as => :import, 
    :via => :post
  

  root :to => 'sessions#home'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ARSIS Online :: Ateneo Resident Student Information System</title>
	<%= favicon_link_tag "ARSALOGO.png" %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%unless session[:user_id]%>
	<%else%>
	<div class="Main_Header">
		
		<table>
			<tr>
				<td width="420" rowspan="2">
					<%= image_tag "arsis-logo.png" %>
				</td>
				<td width="370" align="right" class = "Greeting" align="bottom" >
					<br><br>HELLO</br>
					<%=@current_user.firstname%> <%=@current_user.lastname%></br>
					<%=@current_user.year%> <%=@current_user.course.name%></br>
					<%=@current_user.idnum%>
				</td>
				<td width="80"align="left">
					<br>
					<%= image_tag(@current_user.image.url, :size => "60x60") %>
				</td>
			</tr>
			<tr>

				<td width="490" height="30" colspan="2">

					<ul class="nav">
						<%= image_tag "header/home.png"%> <li><%= link_to :HOME , :home, class: "nav_links"%></li> 
						<%= image_tag "header/contact.png"%> <li><%= link_to :CONTACT , :message, class: "nav_links"%></li> 
						<%= image_tag "headerbuttons/header-logout.png"%> <li><%= link_to :LOGOUT , :logout, class: "nav_links"%></li>	
					</ul>
				</td>
				<td>
				</td>
			</tr>
		</table>
		<%= image_tag "header/navbar.png" %>
		
	</div>
	<%end%>
	<%unless session[:user_id]%>
	<%else%>
	<div class="homebuttons"><br><br>
		<table border="0">
			<tr>
				<td><%= link_to (image_tag "homepagebuttons/button-viewprofile.png", :size => "55x55"), "/profile/#{@current_user.id}" %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-trackprogress.png", :size => "55x55"), "/progress/#{@current_user.id}" %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-viewcalendar.png", :size => "55x55"), :eventcalendar %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-acctsettings.png", :size => "55x55"), setting_path(@current_user.id) %></td>
				<% if @current_user.utype == 'sec_gen' %>
				<td><%= link_to (image_tag "homepagebuttons/button-createevent.png", :size => "55x55"), :newevent %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-myevents.png", :size => "55x55"), :regfile %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-uploadregfile.png", :size => "55x55"), :generatedb %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-generateconsolidated.png", :size => "55x55"), consolidated_path %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-viewlist.png", :size => "55x55"), :dormcouncil %></td>
				<% elsif @current_user.utype == 'dorm_council' %>
				<td><%= link_to (image_tag "homepagebuttons/button-createevent.png", :size => "55x55"), :newevent %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-myevents.png", :size => "55x55"), :regfile %></td>
				<td><%= link_to (image_tag "homepagebuttons/button-viewlist.png", :size => "55x55"), :generatedb %></td>
				<% end %>
			</tr>
			<tr>
				<td align="center">MY PROFILE</td>
				<td align="center">TRACK<br>PROGRESS</td>
				<td align="center">VIEW EVENT<br>CALENDAR</td>
				<td align="center">ACCOUNT<br>SETTINGS</td>
				<% if @current_user.utype == 'sec_gen' %>
				<td align="center">CREATE<BR>EVENT</td>
				<td align="center">UPLOAD<BR>REG FILE</td>
				<td align="center">GENERATE<BR>DORMER LIST</td>
				<td align="center">GENERATE<BR>REPORT</td>
				<td align="center">VIEW DORM<BR>COUNCIL</td>
				<% elsif @current_user.utype == 'dorm_council' %>
				<td align="center">CREATE<BR>EVENT</td>
				<td align="center">UPLOAD<BR>REG FILE</td>
				<td align="center">VIEW ALL<br>DORMERS</td>
				<% end %>
			</tr>


		</table>
	</div>
	<%end%>
	<%unless session[:user_id]%>
		<div class="Login_Notice">
		<% if flash[:color]== "invalid"%>
		<div class="invalid_notice">
			<p><%=flash[:notice]%></p>
		</div>
		<%end%>

		<% if flash[:color]== "valid" %>
		<div class="valid_notice">
			<p><%= flash[:notice]%></p>
		</div>
		<%elsif flash[:color]==nil%>
		<div class="notice">
			<p><%=flash[:notice]%></p>
		</div>
		<%end%>
	</div>
	<%else%>
	
		<% if flash[:color]== "invalid"%>
		<div class="invalid_notice">
			<p><%=flash[:notice]%></p>
		</div>
		<%end%>

		<% if flash[:color]== "valid" %>
		<div class="valid_notice">
			<p><%= flash[:notice]%></p>
		</div>
		<%elsif flash[:color]==nil%>
		<div class="notice">
			<p><%=flash[:notice]%></p>
		</div>
		<%end%>
	<%end%>
	<%= yield %>


	<%unless session[:user_id]%>
	<%else%>
	<div class="Main_Footer">
		<%= image_tag "header/navbar.png" %>
		<div class="nav2">
			<table border="0">
				<tr>
					<td width="780">
						<div align="right">
							<h1><small>(C) 2013 ATENEO RESIDENT STUDENTS ASSOCIATION. ALL RIGHTS RESERVED.<br>
								MAINTAINED BY THE OFFICE OF THE SECRETARY-GENERAL<br>
								DEVELOPED BY SAI & CO.<br></small>
							</h1>
						</div>
					</td>
					<td>
						<%= image_tag "saico.png" %>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<% end %>
</body>
</html>